# Prometheus Alerting Rules
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: llm-d-sre-alerts
  namespace: monitoring
spec:
  groups:
  - name: llm-d.critical
    interval: 30s
    rules:
    - alert: LLMDServiceDown
      expr: up{job="llm-d-service"} == 0
      for: 1m
      labels:
        severity: critical
        service: llm-d
        team: sre
      annotations:
        summary: "LLM-D service is down"
        description: "LLM-D service {{ $labels.instance }} has been down for more than 1 minute"
        runbook_url: "https://runbooks.company.com/llm-d/service-down"
        
    - alert: LLMDHighErrorRate
      expr: |
        (
          sum(rate(llm_d_requests_total{status=~"5.."}[5m])) /
          sum(rate(llm_d_requests_total[5m]))
        ) * 100 > 5
      for: 2m
      labels:
        severity: critical
        service: llm-d
        team: sre
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value }}% over the last 5 minutes"
        runbook_url: "https://runbooks.company.com/llm-d/high-error-rate"
        
    - alert: LLMDHighLatency
      expr: |
        histogram_quantile(0.95, 
          rate(llm_d_request_duration_seconds_bucket[5m])
        ) > 3
      for: 5m
      labels:
        severity: warning
        service: llm-d
        team: sre
      annotations:
        summary: "High inference latency detected"
        description: "95th percentile latency is {{ $value }}s"
        runbook_url: "https://runbooks.company.com/llm-d/high-latency"

  - name: llm-d.capacity
    interval: 60s
    rules:
    - alert: LLMDGPUHighUtilization
      expr: avg(llm_d_gpu_utilization) > 85
      for: 10m
      labels:
        severity: warning
        service: llm-d
        team: sre
      annotations:
        summary: "High GPU utilization detected"
        description: "Average GPU utilization is {{ $value }}%"
        runbook_url: "https://runbooks.company.com/llm-d/gpu-utilization"
        
    - alert: LLMDMemoryPressure
      expr: avg(llm_d_memory_utilization) > 90
      for: 5m
      labels:
        severity: critical
        service: llm-d
        team: sre
      annotations:
        summary: "Memory pressure detected"
        description: "Memory utilization is {{ $value }}%"
        runbook_url: "https://runbooks.company.com/llm-d/memory-pressure"
        
    - alert: LLMDKVCacheOverflow
      expr: llm_d_kv_cache_evictions_total > 100
      for: 5m
      labels:
        severity: warning
        service: llm-d
        team: sre
      annotations:
        summary: "High KV cache eviction rate"
        description: "KV cache evictions: {{ $value }} in last 5 minutes"
        runbook_url: "https://runbooks.company.com/llm-d/cache-evictions"