version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jeremyeder"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group related updates to reduce PR noise
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "cspell"
          - "markdownlint-cli"
          - "@types/*"
          - "eslint*"
          - "prettier*"
        update-types:
          - "minor" 
          - "patch"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jeremyeder"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"