version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jeremyeder"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group related updates to reduce PR noise
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "cspell"
          - "markdownlint-cli"
          - "@types/*"
          - "eslint*"
          - "prettier*"
        update-types:
          - "minor" 
          - "patch"

  # Enable version updates for pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jeremyeder"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps(python)"
      include: "scope"
    groups:
      testing-deps:
        patterns:
          - "pytest*"
          - "coverage*"
          - "*test*"
        update-types:
          - "minor"
          - "patch"
      ml-deps:
        patterns:
          - "numpy"
          - "pandas"
          - "scikit-learn"
          - "matplotlib"
          - "mlflow"
        update-types:
          - "minor"
          - "patch"
      k8s-deps:
        patterns:
          - "kubernetes"
          - "pyyaml"
          - "aiohttp"
        update-types:
          - "minor"
          - "patch"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jeremyeder"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"