name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        
    - name: Run tests with pytest (temporarily disabled)
      run: |
        echo "Pytest tests temporarily disabled"
        # pytest --cov=examples --cov=docs/cost-optimization --cov=docs/security-configs \
        #        --cov-report=xml --cov-report=term-missing \
        #        --junit-xml=pytest-results.xml
               
    - name: Upload coverage to Codecov (temporarily disabled)
      run: |
        echo "Codecov upload temporarily disabled"
      # uses: codecov/codecov-action@v4
      # with:
      #   file: ./coverage.xml
      #   flags: python
      #   name: codecov-umbrella
        
    - name: Upload test results (temporarily disabled)
      run: |
        echo "Test results upload temporarily disabled"
      # uses: actions/upload-artifact@v4
      # if: always()
      # with:
      #   name: pytest-results-${{ matrix.python-version }}
      #   path: pytest-results.xml

  test-docusaurus:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Docusaurus site
      run: npm run build
      
    - name: Test serve
      run: |
        npm run serve &
        sleep 10
        curl -f http://localhost:3000/ || exit 1
        pkill -f "docusaurus serve"

  validate-content:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint markdown
      run: npm run lint
      
    - name: Spell check
      run: npm run spell
      
    - name: Run validation scripts
      run: |
        chmod +x scripts/*.sh
        ./scripts/run-all-validations.sh

  validate-costs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas
        
    - name: Make scripts executable
      run: |
        chmod +x scripts/validate-*.sh
        
    - name: Validate cost calculations in documentation
      run: |
        echo "🔍 Validating cost calculations in documentation..."
        if [ -f docs/11-cost-optimization.md ]; then
          ./scripts/validate-model-names.sh docs/11-cost-optimization.md || echo "Model validation completed with warnings"
          ./scripts/validate-namespaces.sh docs/11-cost-optimization.md || echo "Namespace validation completed with warnings"  
          ./scripts/validate-resource-specs.sh docs/11-cost-optimization.md || echo "Resource spec validation completed with warnings"
        else
          echo "Cost optimization documentation not found, skipping validation"
        fi

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan on Python dependencies
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: requirements-test.txt
        
    - name: Run npm audit
      run: npm audit --audit-level=high --production